### ISSUE TITLE
start making releases

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#180]
I was thinking, what about starting making tagged releases  (or even just tagging on github) ?

It's a bit of work, but it would :

- make the install process a bit easier
- simplify third-party packaging (I'm thinking about https://github.com/YunoHost-Apps/ihatemoney_ynh )
- force us to keep track of changes in a ChangeLog

What do you think ?

**Comment by almet** [comment]
I'm in favor of releases as well :-)

**Comment by JocelynDelalande** [comment]
We now have a mechanism for making realeases (#182) … But we still didn't produce any.

@almet ok if I release a 1.0 with current code ? I would use the tagging mechanism you set but I won't release this version on pypi (for reasons we discussed [before](https://github.com/spiral-project/ihatemoney/pull/182#issuecomment-289809693)).

To tell the full story, I need a tag/release to improve [the yunohost package for ihatemoney](https://github.com/YunoHost-Apps/ihatemoney_ynh)

**Comment by almet** [comment]
I think the thing we need now is a roadmap :-)

if you need a release, make one, for sure! I would probably wait us to merge the settings change before 1.0 though. So maybe 0.9 ? And we can issue 1.0 shortly after once ready.

**Comment by JocelynDelalande** [comment]
Ok, just released [0.9](https://github.com/spiral-project/ihatemoney/releases/tag/0.9) despite #194 .

I leave this issue open for a few days, to see if this release process is ok for now or if we have comments/improvement suggestion. 

I followed strictly what our README.md release section. The *zest.releaser* wizard is pretty clear (I answered *yes* everywhere except for pypi release).

What I'd like to improve on next release is signing (gpg) the git releases.

**Comment by 0livd** [comment]
Should we release version 1.0 ? Now that the design on mobile has been fixed and that #193 is merged

**Comment by JocelynDelalande** [comment]
I'd vote yes, let's 1.0 :-)

**Comment by almet** [comment]
Yes ! I'll let you the honor @JocelynDelalande, if that's okay for you?

**Comment by JocelynDelalande** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alexis Metaireau <notifications@github.com> wrote:
> Yes ! I'll let you the honor @JocelynDelalande, if that's okay
> for you?

With great pleasure, I will be able to update my my yunohost
package to back on that 1.0 right after :-)

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAEBCgAGBQJZRa/0AAoJEOodh6AvlLNT4GYP/2ikgtDrPwBbefJ3rlQd1ddn
eWlk1Qb4TdYasknmd6L2mS3N4tvqBsQFjnO7OIVGwoXDOjSRupJmZZTNVAY+Q8Ky
JVZfOEx7o18ow/rDi3EEVlyp/SvzjueUficRb3GhW1UbPwdjG6j1qI85DJHn1MHr
s+DX5nk70ky/kpDJGohjgG+rc8dU5FMANNxVNCEwh5kORV5vHfNiZz069mD2t/mg
ycRncB3sC1V98leoN3FA5zxXzTb0z9aE9bCRs41etgcRlslYrOBSLAQ7OYS1I0bW
2c4GFBWEecHHFQHW6S4onRu54CMkoNzSGKOGBA2zSfN1uhBg1Gz55OjYoDtKUXwX
QqFrLzfvOXg7Pf806qMmPadRBzmX5sXa807rIVbNQ1LGEVMmDjcuBC6HQAf7qF9B
xE22lr1N6yrWUowqJMrgcJepIz2a1NmjMvzGU3gGNUN2fg7ur3sNnTDw+/t4zYaf
TtuclJM+mdjWD40i5MfnvqsFFw+eluJA0f6Ir9473QORocm92EtIn3VSUm9tzbp4
t1yhbaT0H0lEwv0fR7EPErJYnKKjGZ+Y0Z1tWXx+6vZqCcIdwqvh5RtNBr8uF6U5
IFNZO2gyKjDePdshbkWNjb9r3zbM1u/Ou0MAPMxNgnBzYvKJyKRp/8T5Z3hMU6OO
Qy1gnZBWKDtQFKw4Rvk6
=C7iV
-----END PGP SIGNATURE-----

**Comment by 0livd** [comment]
Would be nice to merge these 2 small fixes before releasing :) #217 #218

**Comment by almet** [comment]
Done :)

**Comment by JocelynDelalande** [comment]
Huray, thanks :-)

Closing.

**Comment by JocelynDelalande** [comment]
Oh, but the release is not done yet, I misread you, sorry.

**Comment by almet** [comment]
Thanks for taking care of it :)

**Comment by JocelynDelalande** [comment]
@almet I still don't have rights on pypi to upload, could you manage to grant me those please ? (username *jocelynd*)

**Comment by almet** [comment]
It's done!

**Comment by JocelynDelalande** [comment]
> It's done!


1.0 is alive !

https://pypi.python.org/pypi/ihatemoney

**Comment by almet** [comment]
Hooray!

**Comment by 0livd** [comment]
nice job ! :)

**Comment by almet** [comment]
Closing, thanks to everyone involved!
